### ISSUE TITLE
Ship a basic Firefox add-on

### ISSUE THREAD

**Issue by OpenMatt** [OpenMatt/GitDone#5]
cc @phillipadsmith @darrenmothersele @darrenmothersele @davidascher @simonwex
see: https://github.com/OpenMatt/GitDone/blob/master/clean-up.css + 
https://github.com/OpenMatt/GitDone/blob/master/manifest.json

**Comment by davidascher** [comment]
What's the add-on for?

**Comment by OpenMatt** [comment]
This: https://github.com/OpenMatt/GitDone/blob/master/README.md

**Comment by phillipadsmith** [comment]
Hey there @davidascher --

We're working toward a basic FF web extension that demonstrates the UI simplification that @OpenMatt's outlined. 

We're also exploring the idea of a boilerplate/template for add-ons that is already set-up to interact with GitHub using [GitHub.js](https://github.com/michael/github) and a public [Gatekeeper](https://github.com/prose/gatekeeper) instance for testing. The hope would be to make it easier for others to get up-and-running quickly with a cross-platform extension that can work with GitHub.

Keen to hear input on the above. :-)

**Comment by davidascher** [comment]
Sorry I had to bolt from the session.  I'll try and get a debrief from some
of you.

I'd love to understand more about some of the design goals.  In particular,
I'd like to understand better what those github traits that are attractive
and repulsive, because add-ons are one of many possible ways of mediating
those.  I'd in particular like to understand whether the goals are to make
a simpler issues management experience, or an onramp onto 'the real'
github, or to find ways for non-dev to interact with devs productively on a
shared platform, or…

When thinking about add-ons, know that web extensions is an emerging model
for doing addons for firefox that should make it easier to make addons for
chrome as well, which is pretty cool.

**Comment by phillipadsmith** [comment]
> When thinking about add-ons, know that web extensions is an emerging model
> for doing addons for firefox that should make it easier to make addons for
> chrome as well, which is pretty cool.

It is pretty cool, indeed! That's what we're currently exploring... 

I'll let @OpenMatt respond to the design goals. :-)

**Comment by OpenMatt** [comment]
@davidascher re design goals: I'll write a post. Good questions.
- this ticket is hand-wavey and not granular enough to be useful. Will close and @phillipadsmith and I will re-file some new ones.
